//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.image` struct is generated, and contains static references to 21 images.
  struct image {
    /// Image `LaunchImage`.
    static let launchImage = Rswift.ImageResource(bundle: R.hostingBundle, name: "LaunchImage")
    /// Image `borsh`.
    static let borsh = Rswift.ImageResource(bundle: R.hostingBundle, name: "borsh")
    /// Image `elrest`.
    static let elrest = Rswift.ImageResource(bundle: R.hostingBundle, name: "elrest")
    /// Image `emptystar`.
    static let emptystar = Rswift.ImageResource(bundle: R.hostingBundle, name: "emptystar")
    /// Image `filledstar`.
    static let filledstar = Rswift.ImageResource(bundle: R.hostingBundle, name: "filledstar")
    /// Image `food`.
    static let food = Rswift.ImageResource(bundle: R.hostingBundle, name: "food")
    /// Image `fran`.
    static let fran = Rswift.ImageResource(bundle: R.hostingBundle, name: "fran")
    /// Image `fuagra`.
    static let fuagra = Rswift.ImageResource(bundle: R.hostingBundle, name: "fuagra")
    /// Image `greek`.
    static let greek = Rswift.ImageResource(bundle: R.hostingBundle, name: "greek")
    /// Image `ital`.
    static let ital = Rswift.ImageResource(bundle: R.hostingBundle, name: "ital")
    /// Image `jap`.
    static let jap = Rswift.ImageResource(bundle: R.hostingBundle, name: "jap")
    /// Image `location`.
    static let location = Rswift.ImageResource(bundle: R.hostingBundle, name: "location")
    /// Image `losos`.
    static let losos = Rswift.ImageResource(bundle: R.hostingBundle, name: "losos")
    /// Image `maxim`.
    static let maxim = Rswift.ImageResource(bundle: R.hostingBundle, name: "maxim")
    /// Image `near`.
    static let near = Rswift.ImageResource(bundle: R.hostingBundle, name: "near")
    /// Image `palkin`.
    static let palkin = Rswift.ImageResource(bundle: R.hostingBundle, name: "palkin")
    /// Image `pin`.
    static let pin = Rswift.ImageResource(bundle: R.hostingBundle, name: "pin")
    /// Image `rezoto`.
    static let rezoto = Rswift.ImageResource(bundle: R.hostingBundle, name: "rezoto")
    /// Image `spagetti`.
    static let spagetti = Rswift.ImageResource(bundle: R.hostingBundle, name: "spagetti")
    /// Image `steikdenver`.
    static let steikdenver = Rswift.ImageResource(bundle: R.hostingBundle, name: "steikdenver")
    /// Image `zezar`.
    static let zezar = Rswift.ImageResource(bundle: R.hostingBundle, name: "zezar")
    
    /// `UIImage(named: "LaunchImage", bundle: ..., traitCollection: ...)`
    static func launchImage(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launchImage, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "borsh", bundle: ..., traitCollection: ...)`
    static func borsh(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.borsh, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "elrest", bundle: ..., traitCollection: ...)`
    static func elrest(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.elrest, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "emptystar", bundle: ..., traitCollection: ...)`
    static func emptystar(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.emptystar, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "filledstar", bundle: ..., traitCollection: ...)`
    static func filledstar(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.filledstar, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "food", bundle: ..., traitCollection: ...)`
    static func food(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.food, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "fran", bundle: ..., traitCollection: ...)`
    static func fran(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fran, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "fuagra", bundle: ..., traitCollection: ...)`
    static func fuagra(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fuagra, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "greek", bundle: ..., traitCollection: ...)`
    static func greek(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.greek, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ital", bundle: ..., traitCollection: ...)`
    static func ital(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ital, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "jap", bundle: ..., traitCollection: ...)`
    static func jap(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.jap, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "location", bundle: ..., traitCollection: ...)`
    static func location(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.location, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "losos", bundle: ..., traitCollection: ...)`
    static func losos(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.losos, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "maxim", bundle: ..., traitCollection: ...)`
    static func maxim(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.maxim, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "near", bundle: ..., traitCollection: ...)`
    static func near(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.near, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "palkin", bundle: ..., traitCollection: ...)`
    static func palkin(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.palkin, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "pin", bundle: ..., traitCollection: ...)`
    static func pin(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.pin, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "rezoto", bundle: ..., traitCollection: ...)`
    static func rezoto(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.rezoto, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "spagetti", bundle: ..., traitCollection: ...)`
    static func spagetti(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.spagetti, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "steikdenver", bundle: ..., traitCollection: ...)`
    static func steikdenver(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.steikdenver, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "zezar", bundle: ..., traitCollection: ...)`
    static func zezar(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.zezar, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 6 nibs.
  struct nib {
    /// Nib `AddToCartDialog`.
    static let addToCartDialog = _R.nib._AddToCartDialog()
    /// Nib `ImageMenuTVCell`.
    static let imageMenuTVCell = _R.nib._ImageMenuTVCell()
    /// Nib `RestDetailsMapView`.
    static let restDetailsMapView = _R.nib._RestDetailsMapView()
    /// Nib `RestMenuCVC`.
    static let restMenuCVC = _R.nib._RestMenuCVC()
    /// Nib `RestMenuTVC`.
    static let restMenuTVC = _R.nib._RestMenuTVC()
    /// Nib `StarViewContainer`.
    static let starViewContainer = _R.nib._StarViewContainer()
    
    /// `UINib(name: "AddToCartDialog", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.addToCartDialog) instead")
    static func addToCartDialog(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.addToCartDialog)
    }
    
    /// `UINib(name: "ImageMenuTVCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.imageMenuTVCell) instead")
    static func imageMenuTVCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.imageMenuTVCell)
    }
    
    /// `UINib(name: "RestDetailsMapView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.restDetailsMapView) instead")
    static func restDetailsMapView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.restDetailsMapView)
    }
    
    /// `UINib(name: "RestMenuCVC", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.restMenuCVC) instead")
    static func restMenuCVC(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.restMenuCVC)
    }
    
    /// `UINib(name: "RestMenuTVC", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.restMenuTVC) instead")
    static func restMenuTVC(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.restMenuTVC)
    }
    
    /// `UINib(name: "StarViewContainer", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.starViewContainer) instead")
    static func starViewContainer(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.starViewContainer)
    }
    
    static func addToCartDialog(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> AddToCartDialog? {
      return R.nib.addToCartDialog.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? AddToCartDialog
    }
    
    static func imageMenuTVCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ImageMenuTVCell? {
      return R.nib.imageMenuTVCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ImageMenuTVCell
    }
    
    static func restDetailsMapView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> RestDetailsMapView? {
      return R.nib.restDetailsMapView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? RestDetailsMapView
    }
    
    static func restMenuCVC(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> RestMenuCVC? {
      return R.nib.restMenuCVC.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? RestMenuCVC
    }
    
    static func restMenuTVC(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> RestMenuTVC? {
      return R.nib.restMenuTVC.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? RestMenuTVC
    }
    
    static func starViewContainer(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.starViewContainer.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 3 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `RestMenuCVC`.
    static let restMenuCVC: Rswift.ReuseIdentifier<RestMenuCVC> = Rswift.ReuseIdentifier(identifier: "RestMenuCVC")
    /// Reuse identifier `RestMenuCell`.
    static let restMenuCell: Rswift.ReuseIdentifier<RestMenuTVC> = Rswift.ReuseIdentifier(identifier: "RestMenuCell")
    /// Reuse identifier `mainMenuCell`.
    static let mainMenuCell: Rswift.ReuseIdentifier<ImageMenuTVCell> = Rswift.ReuseIdentifier(identifier: "mainMenuCell")
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    /// Storyboard `ClosestRests`.
    static let closestRests = _R.storyboard.closestRests()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    /// Storyboard `RestMenu`.
    static let restMenu = _R.storyboard.restMenu()
    
    /// `UIStoryboard(name: "ClosestRests", bundle: ...)`
    static func closestRests(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.closestRests)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    /// `UIStoryboard(name: "RestMenu", bundle: ...)`
    static func restMenu(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.restMenu)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 3 localization tables.
  struct string {
    /// This `R.string.errors` struct is generated, and contains static references to 2 localization keys.
    struct errors {
      /// Value: Wrong storyboard
      static let storyboard = Rswift.StringResource(key: "storyboard", tableName: "Errors", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Wrong view
      static let view = Rswift.StringResource(key: "view", tableName: "Errors", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: Wrong storyboard
      static func storyboard(_: Void = ()) -> String {
        return NSLocalizedString("storyboard", tableName: "Errors", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Wrong view
      static func view(_: Void = ()) -> String {
        return NSLocalizedString("view", tableName: "Errors", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    /// This `R.string.iDs` struct is generated, and contains static references to 1 localization keys.
    struct iDs {
      /// Value: heroID
      static let heroID = Rswift.StringResource(key: "heroID", tableName: "IDs", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: heroID
      static func heroID(_: Void = ()) -> String {
        return NSLocalizedString("heroID", tableName: "IDs", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    /// This `R.string.localizable` struct is generated, and contains static references to 7 localization keys.
    struct localizable {
      /// Value: Ближайшие рестораны
      static let closestRests = Rswift.StringResource(key: "closestRests", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Вы недавно были в ресторане "Ель"
      static let recent = Rswift.StringResource(key: "recent", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Итальянская кухня
      static let italyFood = Rswift.StringResource(key: "italyFood", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Посмотреть меню
      static let seeMenu = Rswift.StringResource(key: "seeMenu", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Посмотреть на карте
      static let seeOnMap = Rswift.StringResource(key: "seeOnMap", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Французская кухня
      static let franceFood = Rswift.StringResource(key: "franceFood", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Японская кухня
      static let japanFood = Rswift.StringResource(key: "japanFood", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: Ближайшие рестораны
      static func closestRests(_: Void = ()) -> String {
        return NSLocalizedString("closestRests", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Вы недавно были в ресторане "Ель"
      static func recent(_: Void = ()) -> String {
        return NSLocalizedString("recent", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Итальянская кухня
      static func italyFood(_: Void = ()) -> String {
        return NSLocalizedString("italyFood", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Посмотреть меню
      static func seeMenu(_: Void = ()) -> String {
        return NSLocalizedString("seeMenu", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Посмотреть на карте
      static func seeOnMap(_: Void = ()) -> String {
        return NSLocalizedString("seeOnMap", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Французская кухня
      static func franceFood(_: Void = ()) -> String {
        return NSLocalizedString("franceFood", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Японская кухня
      static func japanFood(_: Void = ()) -> String {
        return NSLocalizedString("japanFood", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
    try nib.validate()
  }
  
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _RestDetailsMapView.validate()
      try _StarViewContainer.validate()
    }
    
    struct _AddToCartDialog: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "AddToCartDialog"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> AddToCartDialog? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? AddToCartDialog
      }
      
      fileprivate init() {}
    }
    
    struct _ImageMenuTVCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = ImageMenuTVCell
      
      let bundle = R.hostingBundle
      let identifier = "mainMenuCell"
      let name = "ImageMenuTVCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ImageMenuTVCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ImageMenuTVCell
      }
      
      fileprivate init() {}
    }
    
    struct _RestDetailsMapView: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "RestDetailsMapView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> RestDetailsMapView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? RestDetailsMapView
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "elrest", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'elrest' is used in nib 'RestDetailsMapView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "emptystar", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'emptystar' is used in nib 'RestDetailsMapView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "filledstar", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'filledstar' is used in nib 'RestDetailsMapView', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct _RestMenuCVC: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = RestMenuCVC
      
      let bundle = R.hostingBundle
      let identifier = "RestMenuCVC"
      let name = "RestMenuCVC"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> RestMenuCVC? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? RestMenuCVC
      }
      
      fileprivate init() {}
    }
    
    struct _RestMenuTVC: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = RestMenuTVC
      
      let bundle = R.hostingBundle
      let identifier = "RestMenuCell"
      let name = "RestMenuTVC"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> RestMenuTVC? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? RestMenuTVC
      }
      
      fileprivate init() {}
    }
    
    struct _StarViewContainer: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "StarViewContainer"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "filledstar", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'filledstar' is used in nib 'StarViewContainer', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try closestRests.validate()
      try main.validate()
      try restMenu.validate()
    }
    
    struct closestRests: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = ClosestRestsVC
      
      let bundle = R.hostingBundle
      let name = "ClosestRests"
      
      static func validate() throws {
        if UIKit.UIImage(named: "location", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'location' is used in storyboard 'ClosestRests', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct restMenu: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = RestMenuVC
      
      let bundle = R.hostingBundle
      let name = "RestMenu"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
